package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tfindley/syscert/internal/config"
)

// dropInDir/dropInFile is where the generated sandbox grant lives. A drop-in
// rather than an edit of the shipped unit, so a package upgrade replacing
// syscert.service cannot silently drop the grant and break distribution.
const (
	dropInDir  = "/etc/systemd/system/syscert.service.d"
	dropInFile = "10-distribute-paths.conf"
)

// distributeDirs returns the directories the service must be able to write,
// deduplicated and ordered: the store, each distribute target's parent, and any
// [observe] output directory. ProtectSystem=strict leaves everything else
// read-only, so this is exactly the set that has to appear in ReadWritePaths.
//
// The observe outputs belong here for the same reason the targets do — a
// node_exporter textfile directory or /etc/ansible/facts.d is just as far
// outside the store, and just as root-owned, as /etc/cockpit/ws-certs.d.
func distributeDirs(cfg *config.Config) []string {
	seen := map[string]bool{}
	var dirs []string
	add := func(d string) {
		if d == "" || seen[d] {
			return
		}
		seen[d] = true
		dirs = append(dirs, d)
	}
	add(cfg.Store.Path)
	for _, d := range outputDirs(cfg) {
		add(d)
	}
	if len(dirs) > 1 {
		sort.Strings(dirs[1:]) // keep the store first, order the rest for stable output
	}
	return dirs
}

// outputDirs is every directory syscert writes to OUTSIDE the store: each
// distribute target's parent, plus any [observe] output. Shared by the sandbox
// grant and the writability preflight so the two can never disagree about what
// needs to be writable.
func outputDirs(cfg *config.Config) []string {
	seen := map[string]bool{}
	var dirs []string
	add := func(d string) {
		if d == "" || d == "." || seen[d] {
			return
		}
		seen[d] = true
		dirs = append(dirs, d)
	}
	for _, t := range cfg.Distribute {
		add(filepath.Dir(t.Path))
	}
	for _, p := range []string{cfg.Observe.MetricsFile, cfg.Observe.AnsibleFactsFile} {
		if p != "" {
			add(filepath.Dir(p))
		}
	}
	return dirs
}

// unsafeGrantDir reports why a directory must not be written into the drop-in,
// or "" when it is fine. Both installers already refuse these shapes; the binary
// that WRITES the unit fragment must refuse them too, or a mistyped
// `path = "/etc/x.pem"` silently widens ProtectSystem=strict to all of /etc —
// the outcome ADR-0048 explicitly rejected. install.sh calls this before its own
// ACL guard runs, so this is the only thing standing between a typo and a
// too-broad sandbox grant.
func unsafeGrantDir(d string) string {
	if !filepath.IsAbs(d) {
		return "not an absolute path"
	}
	// systemd splits ReadWritePaths on whitespace, and a newline would inject a
	// whole directive into the [Service] section.
	if strings.ContainsAny(d, " \t\r\n") {
		return "contains whitespace, which systemd treats as a separator"
	}
	for _, r := range d {
		if r < 0x20 || r == 0x7f {
			return "contains a control character"
		}
	}
	// Same depth rule as packaging/install.sh: at least two path components.
	if len(strings.Split(strings.Trim(d, "/"), "/")) < 2 {
		return "too broad — a whole top-level directory"
	}
	return ""
}

// partitionGrantDirs splits dirs into those safe to grant and the refusals. The
// store is always kept: it is syscert's own directory, created by the installer.
func partitionGrantDirs(dirs []string, store string) (ok []string, refused map[string]string) {
	refused = map[string]string{}
	for _, d := range dirs {
		if d == store {
			ok = append(ok, d)
			continue
		}
		if why := unsafeGrantDir(d); why != "" {
			refused[d] = why
			continue
		}
		ok = append(ok, d)
	}
	return ok, refused
}

// dropInContent renders the systemd drop-in granting write access to dirs.
func dropInContent(dirs []string) string {
	var b strings.Builder
	b.WriteString("# Generated by 'syscert systemd-paths' — do not edit.\n")
	b.WriteString("# ProtectSystem=strict makes the filesystem read-only, so every directory\n")
	b.WriteString("# syscert writes to must be granted here: the store, each [[distribute]]\n")
	b.WriteString("# target's directory, and any [observe] output directory. Re-run after\n")
	b.WriteString("# changing any of those in syscert.toml.\n")
	b.WriteString("[Service]\n")
	for _, d := range dirs {
		fmt.Fprintf(&b, "ReadWritePaths=%s\n", d)
	}
	return b.String()
}

// cmdSystemdPaths prints — or with --write installs — the systemd drop-in that
// lets the sandboxed service write to its configured distribute targets.
func cmdSystemdPaths(args []string, stdout, stderr io.Writer) int {
	fs := newFlagSet("systemd-paths", stderr)
	cfgPath := configFlag(fs)
	write := fs.Bool("write", false, "install the drop-in under "+dropInDir+" (root)")
	dirsOnly := fs.Bool("dirs", false, "print just the directories, one per line")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	cfg, err := loadConfig(*cfgPath)
	if err != nil {
		fmt.Fprintf(stderr, "systemd-paths: load config: %v\n", err)
		return 2
	}
	dirs, refused := partitionGrantDirs(distributeDirs(cfg), cfg.Store.Path)
	for d, why := range refused {
		fmt.Fprintf(stderr, "systemd-paths: refusing %s — %s; fix the path in the config\n", d, why)
	}

	if *dirsOnly {
		for _, d := range dirs {
			fmt.Fprintln(stdout, d)
		}
		return 0
	}
	if !*write {
		fmt.Fprint(stdout, dropInContent(dirs))
		return 0
	}

	if os.Geteuid() != 0 {
		fmt.Fprintln(stderr, "systemd-paths --write: must run as root")
		return 1
	}
	// Refuse to install a grant derived from a config we just objected to —
	// otherwise the typo is written into the unit and only the ACL step complains.
	if len(refused) > 0 {
		fmt.Fprintln(stderr, "systemd-paths --write: refusing to write a drop-in while any directory is unusable")
		return 1
	}
	// #nosec G301 -- a unit drop-in directory must be traversable by systemd; /etc/systemd/system/*.d is 0755 by convention
	if err := os.MkdirAll(dropInDir, 0o755); err != nil {
		fmt.Fprintf(stderr, "systemd-paths: create %s: %v\n", dropInDir, err)
		return 1
	}
	path := filepath.Join(dropInDir, dropInFile)
	if err := os.WriteFile(path, []byte(dropInContent(dirs)), 0o644); err != nil { // #nosec G306 -- a unit drop-in must be world-readable for systemd
		fmt.Fprintf(stderr, "systemd-paths: write %s: %v\n", path, err)
		return 1
	}
	fmt.Fprintf(stdout, "wrote %s granting %d director%s\n", path, len(dirs), plural(len(dirs)))
	// Deliberately not run here: syscert executes only the trust-store update and
	// chcon, and the published security assessment counts those two sites.
	fmt.Fprintln(stdout, "now run: systemctl daemon-reload")
	return 0
}

func plural(n int) string {
	if n == 1 {
		return "y"
	}
	return "ies"
}
