package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tfindley/syscert/internal/config"
)

// dropInDir/dropInFile is where the generated sandbox grant lives. A drop-in
// rather than an edit of the shipped unit, so a package upgrade replacing
// syscert.service cannot silently drop the grant and break distribution.
const (
	dropInDir  = "/etc/systemd/system/syscert.service.d"
	dropInFile = "10-distribute-paths.conf"
)

// distributeDirs returns the directories the service must be able to write,
// deduplicated and ordered: the store, each distribute target's parent, and any
// [observe] output directory. ProtectSystem=strict leaves everything else
// read-only, so this is exactly the set that has to appear in ReadWritePaths.
//
// The observe outputs belong here for the same reason the targets do — a
// node_exporter textfile directory or /etc/ansible/facts.d is just as far
// outside the store, and just as root-owned, as /etc/cockpit/ws-certs.d.
func distributeDirs(cfg *config.Config) []string {
	seen := map[string]bool{}
	var dirs []string
	add := func(d string) {
		if d == "" || seen[d] {
			return
		}
		seen[d] = true
		dirs = append(dirs, d)
	}
	add(cfg.Store.Path)
	for _, d := range outputDirs(cfg) {
		add(d)
	}
	if len(dirs) > 1 {
		sort.Strings(dirs[1:]) // keep the store first, order the rest for stable output
	}
	return dirs
}

// outputDirs is every directory syscert writes to OUTSIDE the store: each
// distribute target's parent, plus any [observe] output. Shared by the sandbox
// grant and the writability preflight so the two can never disagree about what
// needs to be writable.
func outputDirs(cfg *config.Config) []string {
	seen := map[string]bool{}
	var dirs []string
	add := func(d string) {
		if d == "" || d == "." || seen[d] {
			return
		}
		seen[d] = true
		dirs = append(dirs, d)
	}
	for _, t := range cfg.Distribute {
		add(filepath.Dir(t.Path))
	}
	for _, p := range []string{cfg.Observe.MetricsFile, cfg.Observe.AnsibleFactsFile} {
		if p != "" {
			add(filepath.Dir(p))
		}
	}
	return dirs
}

// dropInContent renders the systemd drop-in granting write access to dirs.
func dropInContent(dirs []string) string {
	var b strings.Builder
	b.WriteString("# Generated by 'syscert systemd-paths' — do not edit.\n")
	b.WriteString("# ProtectSystem=strict makes the filesystem read-only, so every directory\n")
	b.WriteString("# syscert writes to must be granted here: the store, each [[distribute]]\n")
	b.WriteString("# target's directory, and any [observe] output directory. Re-run after\n")
	b.WriteString("# changing any of those in syscert.toml.\n")
	b.WriteString("[Service]\n")
	for _, d := range dirs {
		fmt.Fprintf(&b, "ReadWritePaths=%s\n", d)
	}
	return b.String()
}

// cmdSystemdPaths prints — or with --write installs — the systemd drop-in that
// lets the sandboxed service write to its configured distribute targets.
func cmdSystemdPaths(args []string, stdout, stderr io.Writer) int {
	fs := newFlagSet("systemd-paths", stderr)
	cfgPath := configFlag(fs)
	write := fs.Bool("write", false, "install the drop-in under "+dropInDir+" (root)")
	dirsOnly := fs.Bool("dirs", false, "print just the directories, one per line")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	cfg, err := loadConfig(*cfgPath)
	if err != nil {
		fmt.Fprintf(stderr, "systemd-paths: load config: %v\n", err)
		return 2
	}
	dirs := distributeDirs(cfg)

	if *dirsOnly {
		for _, d := range dirs {
			fmt.Fprintln(stdout, d)
		}
		return 0
	}
	if !*write {
		fmt.Fprint(stdout, dropInContent(dirs))
		return 0
	}

	if os.Geteuid() != 0 {
		fmt.Fprintln(stderr, "systemd-paths --write: must run as root")
		return 1
	}
	// #nosec G301 -- a unit drop-in directory must be traversable by systemd; /etc/systemd/system/*.d is 0755 by convention
	if err := os.MkdirAll(dropInDir, 0o755); err != nil {
		fmt.Fprintf(stderr, "systemd-paths: create %s: %v\n", dropInDir, err)
		return 1
	}
	path := filepath.Join(dropInDir, dropInFile)
	if err := os.WriteFile(path, []byte(dropInContent(dirs)), 0o644); err != nil { // #nosec G306 -- a unit drop-in must be world-readable for systemd
		fmt.Fprintf(stderr, "systemd-paths: write %s: %v\n", path, err)
		return 1
	}
	fmt.Fprintf(stdout, "wrote %s granting %d director%s\n", path, len(dirs), plural(len(dirs)))
	// Deliberately not run here: syscert executes only the trust-store update and
	// chcon, and the published security assessment counts those two sites.
	fmt.Fprintln(stdout, "now run: systemctl daemon-reload")
	return 0
}

func plural(n int) string {
	if n == 1 {
		return "y"
	}
	return "ies"
}
