---
- name: syscert.secrets - Render the secrets environment file
  become: true
  no_log: true
  ansible.builtin.template:
    src: secrets.j2
    dest: "{{ syscert_secrets_path }}"
    owner: root
    group: "{{ syscert_group }}"
    mode: "0640"
